scrape_configs:
  - job_name: 'prometheus-project'
    static_configs:
    - targets: ['localhost:9090']
    
  - job_name: 'spring-actuator-project'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:8080']